package zaliczenie.Hosting_photos;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter;
import com.vaadin.annotations.AutoGenerated;
@SpringBootApplication
@ComponentScan({ "zaliczenie.Hosting_photos","zaliczenie.Hosting_photos.gui","zaliczenie.Hosting_photos.service","zaliczenie.Hosting_photos.model","zaliczenie.Hosting_photos.repo"})
public class HostingPhotosApplication {

	public static void main(String[] args) {
		SpringApplication.run(HostingPhotosApplication.class, args);
	}

	@Bean
	public WebMvcConfigurer corsConfigurer() {
		return new WebMvcConfigurerAdapter() {
			@Override
			public void addCorsMappings(CorsRegistry registry) {

				registry.addMapping("/**");
			}
		};
	}

}
